FROM node:alpine

#we are specifying the user who will run the commands. 
#The project files are also being copied to this user's home directory
USER node
RUN mkdir -p /home/node/app

WORKDIR "/home/node/app"
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node . .

CMD ["npm", "start"]